spring:
  application:
    name: service-center

  datasource:
    url: jdbc:postgresql://localhost:5432/service_center
    username: sc_user
    password: sc_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: PLACEHOLDER
            client-secret: PLACEHOLDER
            scope: user:email, read:user

server:
  port: 8080

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    org.springframework.security: DEBUG
    by.bguir: DEBUG